// WARNING: 本文件由 scripts/gen-bindings.cjs 生成，请勿手改。
export function GetBookmarks(filePath: any): Promise<any>;
export function GetAllBookmarks(): Promise<any>;
export function AddBookmark(filePath: any, lineNumber: any, note: any, tag: any): Promise<any>;
export function RemoveBookmark(id: any): Promise<any>;
export function UpdateBookmarkNote(id: any, note: any): Promise<any>;
export function UpdateBookmarkTag(id: any, tag: any): Promise<any>;
export function CompareDirectories(leftDir: any, rightDir: any): Promise<any>;
export function BinaryCompare(leftPath: any, rightPath: any): Promise<any>;
export function GetConfig(): Promise<any>;
export function UpdateConfig(newConfig: any): Promise<any>;
export function SetCloseToTray(enabled: any): Promise<any>;
export function ForceQuit(): Promise<any>;
export function GetSetting(key: any): Promise<any>;
export function SetSetting(key: any, value: any): Promise<any>;
export function AddFavorite(path: any): Promise<any>;
export function RemoveFavorite(path: any): Promise<any>;
export function GetFavorites(): Promise<any>;
export function Convert(content: any, fromFmt: any, toFmt: any): Promise<any>;
export function ShowMessageDialog(title: any, message: any, dialogType: any): Promise<any>;
export function ShowConfirmDialog(title: any, message: any): Promise<any>;
export function GetAppVersion(): Promise<any>;
export function GetSystemInfo(): Promise<any>;
export function Exit(): Promise<any>;
export function CompareDiff(oldText: any, newText: any): Promise<any>;
export function CompareDiffLines(oldText: any, newText: any): Promise<any>;
export function GetDiffPatch(oldText: any, newText: any): Promise<any>;
export function ApplyDiffPatch(text: any, patch: any): Promise<any>;
export function CompareCharacters(oldStr: any, newStr: any): Promise<any>;
export function OpenDirectoryDialog(): Promise<any>;
export function GetDirectoryTree(path: any): Promise<any>;
export function CreateDirectory(path: any): Promise<any>;
export function ListDirectory(path: any): Promise<any>;
export function AutoSaveDraft(filePath: any, content: any, encoding: any, lineEnding: any): Promise<any>;
export function GetDraft(filePath: any): Promise<any>;
export function ListDrafts(): Promise<any>;
export function DeleteDraft(filePath: any): Promise<any>;
export function ClearAllDrafts(): Promise<any>;
export function CheckDraftConflict(filePath: any): Promise<any>;
export function GetSupportedEncodings(): Promise<any>;
export function ConvertEncoding(content: any, fromEncoding: any, toEncoding: any): Promise<any>;
export function DetectEncoding(content: any): Promise<any>;
export function ConvertToUTF8(content: any, fromEncoding: any): Promise<any>;
export function ConvertFromUTF8(content: any, toEncoding: any): Promise<any>;
export function HasBOM(content: any): Promise<any>;
export function RemoveBOM(content: any): Promise<any>;
export function AddBOM(content: any, encoding: any): Promise<any>;
export function OpenFileDialog(): Promise<any>;
export function SaveFileDialog(defaultFilename: any): Promise<any>;
export function ReadFile(path: any): Promise<any>;
export function ReadPartial(path: any, offset: any, count: any): Promise<any>;
export function SaveFile(path: any, content: any, encoding: any): Promise<any>;
export function SaveFileWithBackup(path: any, content: any, encoding: any): Promise<any>;
export function GetFileInfo(path: any): Promise<any>;
export function DeleteFile(path: any): Promise<any>;
export function DeleteDirectory(path: any): Promise<any>;
export function RenameFile(oldPath: any, newPath: any): Promise<any>;
export function CopyFile(src: any, dst: any): Promise<any>;
export function IsBinaryFile(path: any): Promise<any>;
export function ReadFileBytes(path: any): Promise<any>;
export function ReadFileChunk(path: any, offset: any, size: any): Promise<any>;
export function SaveFileBytes(path: any, data: any): Promise<any>;
export function StartFileWatch(path: any): Promise<any>;
export function StopFileWatch(path: any): Promise<any>;
export function FindInFile(filePath: any, search: any, options: any): Promise<any>;
export function FindInDirectory(dirPath: any, search: any, options: any): Promise<any>;
export function ReplaceInFile(filePath: any, search: any, replace: any, options: any): Promise<any>;
export function BatchReplace(dirPath: any, options: any): Promise<any>;
export function SearchInFiles(filePaths: any, search: any, options: any): Promise<any>;
export function ReplaceInFiles(filePaths: any, search: any, replace: any, options: any): Promise<any>;
export function ComputeHash(content: any): Promise<any>;
export function ComputeFileHash(filePath: any): Promise<any>;
export function ComputeHashWithAlgo(content: any, algorithm: any): Promise<any>;
export function ComputeFileHashWithAlgo(filePath: any, algorithm: any): Promise<any>;
export function FormatJSON(content: any, indentSize: any): Promise<any>;
export function MinifyJSON(content: any): Promise<any>;
export function ValidateJSON(content: any): Promise<any>;
export function FlattenJSON(content: any, separator: any): Promise<any>;
export function ExtractJSONKeys(content: any): Promise<any>;
export function JsonPathQuery(jsonStr: any, path: any): Promise<any>;
export function JsonToStruct(jsonStr: any, lang: any, rootName: any): Promise<any>;
export function JsonStructuredDiff(leftJSON: any, rightJSON: any): Promise<any>;
export function StartMacroRecording(): Promise<any>;
export function StopMacroRecording(): Promise<any>;
export function RecordMacroStep(step: any): Promise<any>;
export function GetMacros(): Promise<any>;
export function DeleteMacro(id: any): Promise<any>;
export function RenameMacro(id: any, newName: any): Promise<any>;
export function IsMacroRecording(): Promise<any>;
export function SaveCurrentMacro(name: any): Promise<any>;
export function TestRegex(pattern: any, flags: any, input: any): Promise<any>;
export function ValidateRegex(pattern: any): Promise<any>;
export function EscapeRegex(input: any): Promise<any>;
export function BatchRenamePreview(files: any, pattern: any, startIndex: any, step: any, delimiter: any): Promise<any>;
export function BatchRenameExecute(preview: any): Promise<any>;
export function GetCommonNamePatterns(): Promise<any>;
export function ListScripts(): Promise<any>;
export function GetScript(id: any): Promise<any>;
export function SaveScript(script: any): Promise<any>;
export function DeleteScript(id: any): Promise<any>;
export function ExecuteScript(id: any, context: any): Promise<any>;
export function SaveSession(files: any, activeID: any): Promise<any>;
export function GetSession(): Promise<any>;
export function GetSnippets(language: any): Promise<any>;
export function CreateSnippet(entry: any): Promise<any>;
export function UpdateSnippet(entry: any): Promise<any>;
export function DeleteSnippet(id: any): Promise<any>;
export function ImportSnippets(jsonData: any): Promise<any>;
export function ExportSnippets(): Promise<any>;
export function GetRecentFiles(): Promise<any>;
export function GetRecentFolders(): Promise<any>;
export function AddRecentEntry(path: any, isFolder: any): Promise<any>;
export function ClearRecentFiles(): Promise<any>;
export function ClearRecentFolders(): Promise<any>;
export function RegisterFileAssoc(): Promise<any>;
export function UnregisterFileAssoc(): Promise<any>;
export function IsFileAssocRegistered(): Promise<any>;
