// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBOM(arg1, arg2) {
  return window['go']['main']['App']['AddBOM'](arg1, arg2);
}

export function AddBookmark(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddBookmark'](arg1, arg2, arg3, arg4);
}

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function AddRecentEntry(arg1, arg2) {
  return window['go']['main']['App']['AddRecentEntry'](arg1, arg2);
}

export function ApplyDiffPatch(arg1, arg2) {
  return window['go']['main']['App']['ApplyDiffPatch'](arg1, arg2);
}

export function AutoSaveDraft(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AutoSaveDraft'](arg1, arg2, arg3, arg4);
}

export function BatchRenameExecute(arg1) {
  return window['go']['main']['App']['BatchRenameExecute'](arg1);
}

export function BatchRenamePreview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BatchRenamePreview'](arg1, arg2, arg3, arg4, arg5);
}

export function BatchReplace(arg1, arg2) {
  return window['go']['main']['App']['BatchReplace'](arg1, arg2);
}

export function BinaryCompare(arg1, arg2) {
  return window['go']['main']['App']['BinaryCompare'](arg1, arg2);
}

export function CheckDraftConflict(arg1) {
  return window['go']['main']['App']['CheckDraftConflict'](arg1);
}

export function ClearAllDrafts() {
  return window['go']['main']['App']['ClearAllDrafts']();
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ClearRecentFolders() {
  return window['go']['main']['App']['ClearRecentFolders']();
}

export function CompareCharacters(arg1, arg2) {
  return window['go']['main']['App']['CompareCharacters'](arg1, arg2);
}

export function CompareDiff(arg1, arg2) {
  return window['go']['main']['App']['CompareDiff'](arg1, arg2);
}

export function CompareDiffLines(arg1, arg2) {
  return window['go']['main']['App']['CompareDiffLines'](arg1, arg2);
}

export function CompareDirectories(arg1, arg2) {
  return window['go']['main']['App']['CompareDirectories'](arg1, arg2);
}

export function ComputeFileHash(arg1) {
  return window['go']['main']['App']['ComputeFileHash'](arg1);
}

export function ComputeFileHashWithAlgo(arg1, arg2) {
  return window['go']['main']['App']['ComputeFileHashWithAlgo'](arg1, arg2);
}

export function ComputeHash(arg1) {
  return window['go']['main']['App']['ComputeHash'](arg1);
}

export function ComputeHashWithAlgo(arg1, arg2) {
  return window['go']['main']['App']['ComputeHashWithAlgo'](arg1, arg2);
}

export function Convert(arg1, arg2, arg3) {
  return window['go']['main']['App']['Convert'](arg1, arg2, arg3);
}

export function ConvertEncoding(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertEncoding'](arg1, arg2, arg3);
}

export function ConvertFromUTF8(arg1, arg2) {
  return window['go']['main']['App']['ConvertFromUTF8'](arg1, arg2);
}

export function ConvertToUTF8(arg1, arg2) {
  return window['go']['main']['App']['ConvertToUTF8'](arg1, arg2);
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateSnippet(arg1) {
  return window['go']['main']['App']['CreateSnippet'](arg1);
}

export function DeleteDirectory(arg1) {
  return window['go']['main']['App']['DeleteDirectory'](arg1);
}

export function DeleteDraft(arg1) {
  return window['go']['main']['App']['DeleteDraft'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteMacro(arg1) {
  return window['go']['main']['App']['DeleteMacro'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['main']['App']['DeleteScript'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function DetectEncoding(arg1) {
  return window['go']['main']['App']['DetectEncoding'](arg1);
}

export function EscapeRegex(arg1) {
  return window['go']['main']['App']['EscapeRegex'](arg1);
}

export function ExecuteScript(arg1, arg2) {
  return window['go']['main']['App']['ExecuteScript'](arg1, arg2);
}

export function Exit() {
  return window['go']['main']['App']['Exit']();
}

export function ExportSnippets() {
  return window['go']['main']['App']['ExportSnippets']();
}

export function ExtractJSONKeys(arg1) {
  return window['go']['main']['App']['ExtractJSONKeys'](arg1);
}

export function FindInDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindInDirectory'](arg1, arg2, arg3);
}

export function FindInFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindInFile'](arg1, arg2, arg3);
}

export function FlattenJSON(arg1, arg2) {
  return window['go']['main']['App']['FlattenJSON'](arg1, arg2);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function FormatJSON(arg1, arg2) {
  return window['go']['main']['App']['FormatJSON'](arg1, arg2);
}

export function GetAllBookmarks() {
  return window['go']['main']['App']['GetAllBookmarks']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBookmarks(arg1) {
  return window['go']['main']['App']['GetBookmarks'](arg1);
}

export function GetCommonNamePatterns() {
  return window['go']['main']['App']['GetCommonNamePatterns']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiffPatch(arg1, arg2) {
  return window['go']['main']['App']['GetDiffPatch'](arg1, arg2);
}

export function GetDirectoryTree(arg1) {
  return window['go']['main']['App']['GetDirectoryTree'](arg1);
}

export function GetDraft(arg1) {
  return window['go']['main']['App']['GetDraft'](arg1);
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetMacros() {
  return window['go']['main']['App']['GetMacros']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetRecentFolders() {
  return window['go']['main']['App']['GetRecentFolders']();
}

export function GetScript(arg1) {
  return window['go']['main']['App']['GetScript'](arg1);
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSnippets(arg1) {
  return window['go']['main']['App']['GetSnippets'](arg1);
}

export function GetSupportedEncodings() {
  return window['go']['main']['App']['GetSupportedEncodings']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function HasBOM(arg1) {
  return window['go']['main']['App']['HasBOM'](arg1);
}

export function ImportSnippets(arg1) {
  return window['go']['main']['App']['ImportSnippets'](arg1);
}

export function IsBinaryFile(arg1) {
  return window['go']['main']['App']['IsBinaryFile'](arg1);
}

export function IsFileAssocRegistered() {
  return window['go']['main']['App']['IsFileAssocRegistered']();
}

export function IsMacroRecording() {
  return window['go']['main']['App']['IsMacroRecording']();
}

export function JsonPathQuery(arg1, arg2) {
  return window['go']['main']['App']['JsonPathQuery'](arg1, arg2);
}

export function JsonStructuredDiff(arg1, arg2) {
  return window['go']['main']['App']['JsonStructuredDiff'](arg1, arg2);
}

export function JsonToStruct(arg1, arg2, arg3) {
  return window['go']['main']['App']['JsonToStruct'](arg1, arg2, arg3);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListDrafts() {
  return window['go']['main']['App']['ListDrafts']();
}

export function ListScripts() {
  return window['go']['main']['App']['ListScripts']();
}

export function MinifyJSON(arg1) {
  return window['go']['main']['App']['MinifyJSON'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileBytes(arg1) {
  return window['go']['main']['App']['ReadFileBytes'](arg1);
}

export function ReadFileChunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFileChunk'](arg1, arg2, arg3);
}

export function ReadPartial(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadPartial'](arg1, arg2, arg3);
}

export function RecordMacroStep(arg1) {
  return window['go']['main']['App']['RecordMacroStep'](arg1);
}

export function RegisterFileAssoc() {
  return window['go']['main']['App']['RegisterFileAssoc']();
}

export function RemoveBOM(arg1) {
  return window['go']['main']['App']['RemoveBOM'](arg1);
}

export function RemoveBookmark(arg1) {
  return window['go']['main']['App']['RemoveBookmark'](arg1);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RenameMacro(arg1, arg2) {
  return window['go']['main']['App']['RenameMacro'](arg1, arg2);
}

export function ReplaceInFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplaceInFile'](arg1, arg2, arg3, arg4);
}

export function ReplaceInFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplaceInFiles'](arg1, arg2, arg3, arg4);
}

export function SaveCurrentMacro(arg1) {
  return window['go']['main']['App']['SaveCurrentMacro'](arg1);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SaveFileBytes(arg1, arg2) {
  return window['go']['main']['App']['SaveFileBytes'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveFileWithBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileWithBackup'](arg1, arg2, arg3);
}

export function SaveScript(arg1) {
  return window['go']['main']['App']['SaveScript'](arg1);
}

export function SaveSession(arg1, arg2) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2);
}

export function SearchInFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchInFiles'](arg1, arg2, arg3);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function ShowConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowConfirmDialog'](arg1, arg2);
}

export function ShowMessageDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2, arg3);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function StartFileWatch(arg1) {
  return window['go']['main']['App']['StartFileWatch'](arg1);
}

export function StartMacroRecording() {
  return window['go']['main']['App']['StartMacroRecording']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopFileWatch(arg1) {
  return window['go']['main']['App']['StopFileWatch'](arg1);
}

export function StopMacroRecording() {
  return window['go']['main']['App']['StopMacroRecording']();
}

export function TestRegex(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestRegex'](arg1, arg2, arg3);
}

export function UnregisterFileAssoc() {
  return window['go']['main']['App']['UnregisterFileAssoc']();
}

export function UpdateBookmarkNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateBookmarkNote'](arg1, arg2);
}

export function UpdateBookmarkTag(arg1, arg2) {
  return window['go']['main']['App']['UpdateBookmarkTag'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateSnippet(arg1) {
  return window['go']['main']['App']['UpdateSnippet'](arg1);
}

export function ValidateJSON(arg1) {
  return window['go']['main']['App']['ValidateJSON'](arg1);
}

export function ValidateRegex(arg1) {
  return window['go']['main']['App']['ValidateRegex'](arg1);
}
