// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tools} from '../models';
import {api} from '../models';
import {config} from '../models';
import {file} from '../models';
import {frontend} from '../models';
import {context} from '../models';

export function AddBOM(arg1:Array<number>,arg2:string):Promise<Array<number>>;

export function AddBookmark(arg1:string,arg2:number,arg3:string,arg4:string):Promise<tools.BookmarkEntry>;

export function AddFavorite(arg1:string):Promise<void>;

export function AddRecentEntry(arg1:string,arg2:boolean):Promise<void>;

export function ApplyDiffPatch(arg1:string,arg2:string):Promise<string>;

export function AutoSaveDraft(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function BatchRenameExecute(arg1:api.BatchRenameResult):Promise<api.BatchRenameResult>;

export function BatchRenamePreview(arg1:Array<string>,arg2:string,arg3:number,arg4:number,arg5:string):Promise<api.BatchRenameResult>;

export function BatchReplace(arg1:string,arg2:tools.FindOptions):Promise<number>;

export function BinaryCompare(arg1:string,arg2:string):Promise<tools.BinCompareResult>;

export function CheckDraftConflict(arg1:string):Promise<number>;

export function ClearAllDrafts():Promise<void>;

export function ClearRecentFiles():Promise<void>;

export function ClearRecentFolders():Promise<void>;

export function CompareCharacters(arg1:string,arg2:string):Promise<string>;

export function CompareDiff(arg1:string,arg2:string):Promise<tools.DiffResult>;

export function CompareDiffLines(arg1:string,arg2:string):Promise<Array<tools.DiffBlock>>;

export function CompareDirectories(arg1:string,arg2:string):Promise<tools.DirCompareResult>;

export function ComputeFileHash(arg1:string):Promise<api.HashResult>;

export function ComputeFileHashWithAlgo(arg1:string,arg2:string):Promise<api.HashAlgoResult>;

export function ComputeHash(arg1:string):Promise<api.HashResult>;

export function ComputeHashWithAlgo(arg1:string,arg2:string):Promise<api.HashAlgoResult>;

export function Convert(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ConvertEncoding(arg1:Array<number>,arg2:string,arg3:string):Promise<Array<number>>;

export function ConvertFromUTF8(arg1:string,arg2:string):Promise<Array<number>>;

export function ConvertToUTF8(arg1:Array<number>,arg2:string):Promise<string>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateSnippet(arg1:tools.SnippetEntry):Promise<number>;

export function DeleteDirectory(arg1:string):Promise<void>;

export function DeleteDraft(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteMacro(arg1:string):Promise<boolean>;

export function DeleteScript(arg1:string):Promise<void>;

export function DeleteSnippet(arg1:number):Promise<void>;

export function DetectEncoding(arg1:Array<number>):Promise<string>;

export function EscapeRegex(arg1:string):Promise<string>;

export function ExecuteScript(arg1:string,arg2:tools.ScriptContext):Promise<tools.ScriptResult>;

export function Exit():Promise<void>;

export function ExportSnippets():Promise<string>;

export function ExtractJSONKeys(arg1:string):Promise<Array<string>>;

export function FindInDirectory(arg1:string,arg2:string,arg3:tools.FindOptions):Promise<Array<tools.FindInFileResult>>;

export function FindInFile(arg1:string,arg2:string,arg3:tools.FindOptions):Promise<Array<tools.FindMatch>>;

export function FlattenJSON(arg1:string,arg2:string):Promise<string>;

export function ForceQuit():Promise<void>;

export function FormatJSON(arg1:string,arg2:number):Promise<tools.JSONResult>;

export function GetAllBookmarks():Promise<Record<string, Array<tools.BookmarkEntry>>>;

export function GetAppVersion():Promise<string>;

export function GetBookmarks(arg1:string):Promise<Array<tools.BookmarkEntry>>;

export function GetCommonNamePatterns():Promise<Array<string>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetDiffPatch(arg1:string,arg2:string):Promise<string>;

export function GetDirectoryTree(arg1:string):Promise<file.FileTree>;

export function GetDraft(arg1:string):Promise<tools.DraftEntry>;

export function GetFavorites():Promise<Array<string>>;

export function GetFileInfo(arg1:string):Promise<file.FileInfo>;

export function GetMacros():Promise<Array<tools.Macro>>;

export function GetRecentFiles():Promise<Array<tools.RecentEntryResult>>;

export function GetRecentFolders():Promise<Array<tools.RecentEntryResult>>;

export function GetScript(arg1:string):Promise<tools.ScriptInfo>;

export function GetSession():Promise<api.Session>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSnippets(arg1:string):Promise<Array<tools.SnippetEntry>>;

export function GetSupportedEncodings():Promise<Array<tools.EncodingInfo>>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function HasBOM(arg1:Array<number>):Promise<boolean|string>;

export function ImportSnippets(arg1:string):Promise<number>;

export function IsBinaryFile(arg1:string):Promise<boolean>;

export function IsFileAssocRegistered():Promise<boolean>;

export function IsMacroRecording():Promise<boolean>;

export function JsonPathQuery(arg1:string,arg2:string):Promise<Array<tools.JSONPathResult>>;

export function JsonStructuredDiff(arg1:string,arg2:string):Promise<tools.JSONDiffResult>;

export function JsonToStruct(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<file.FileInfo>>;

export function ListDrafts():Promise<Array<tools.DraftEntry>>;

export function ListScripts():Promise<Array<tools.ScriptInfo>>;

export function MinifyJSON(arg1:string):Promise<tools.JSONResult>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<file.ReadResult>;

export function ReadFileBytes(arg1:string):Promise<Array<number>>;

export function ReadFileChunk(arg1:string,arg2:number,arg3:number):Promise<file.ChunkResult>;

export function ReadPartial(arg1:string,arg2:number,arg3:number):Promise<string>;

export function RecordMacroStep(arg1:tools.MacroStep):Promise<void>;

export function RegisterFileAssoc():Promise<Array<string>>;

export function RemoveBOM(arg1:Array<number>):Promise<Array<number>>;

export function RemoveBookmark(arg1:number):Promise<void>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RenameMacro(arg1:string,arg2:string):Promise<boolean>;

export function ReplaceInFile(arg1:string,arg2:string,arg3:string,arg4:tools.FindOptions):Promise<number>;

export function ReplaceInFiles(arg1:Array<string>,arg2:string,arg3:string,arg4:tools.FindOptions):Promise<number>;

export function SaveCurrentMacro(arg1:string):Promise<tools.Macro>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<file.WriteResult>;

export function SaveFileBytes(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveFileWithBackup(arg1:string,arg2:string,arg3:string):Promise<file.WriteResult>;

export function SaveScript(arg1:tools.ScriptInfo):Promise<void>;

export function SaveSession(arg1:Array<api.SessionFile>,arg2:string):Promise<void>;

export function SearchInFiles(arg1:Array<string>,arg2:string,arg3:tools.FindOptions):Promise<Array<tools.FindInFileResult>>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ShowConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function ShowMessageDialog(arg1:string,arg2:string,arg3:frontend.DialogType):Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartFileWatch(arg1:string):Promise<void>;

export function StartMacroRecording():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopFileWatch(arg1:string):Promise<void>;

export function StopMacroRecording():Promise<tools.Macro>;

export function TestRegex(arg1:string,arg2:string,arg3:string):Promise<tools.RegexTestResult>;

export function UnregisterFileAssoc():Promise<void>;

export function UpdateBookmarkNote(arg1:number,arg2:string):Promise<void>;

export function UpdateBookmarkTag(arg1:number,arg2:string):Promise<void>;

export function UpdateConfig(arg1:config.AppConfig):Promise<void>;

export function UpdateSnippet(arg1:tools.SnippetEntry):Promise<void>;

export function ValidateJSON(arg1:string):Promise<tools.JSONResult>;

export function ValidateRegex(arg1:string):Promise<void>;
